#nodejskubernetesdeployment.yml

apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nodejs-k8s-app-deployment # Name of the deployment
  labels:
    app: nodejs-k8s-app
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: nodejs-k8s-app # Label selector for the pods
  template:
    metadata:
      labels:
        app: nodejs-k8s-app # Label for the pod template
  spec:
     containers:
      - name: nodeserver # Name of the container
        image: jjuma/nodejs-k8s-app:latest # Docker image for the Node.js app
        ports:
        - containerPort: 3000 # Port on which the app listens
